### ISSUE TITLE
models as OCI artefacts support

### ISSUE THREAD

**Issue by ericcurtin** [containers/ramalama#13]
We want to ability to push pull models as OCI artefacts.

We could do this on Linux pretty easily via podman push/pull/build.

A macOS solution for "podman build" is an issue. Although skopeo does push/pull on macOS (apparently, haven't tested)

There are multiple projects that want to place arbitrary data in an OCI artefact, so ideally we'd share a tool among multiple projects, like bootc, etc.

https://github.com/containers/podman/discussions/23421

**Comment by rhatdan** [comment]
For now I would just extend ramalama python code to do this, and use skopeo for pulling and pushing.

**Comment by rhatdan** [comment]
If another tool arises we could take advantage of it, or we make this python code + skopeo into a library that others could use.

**Comment by ericcurtin** [comment]
To be implemented as oci:// (like we have ollama:// and huggingface://):

This looks like it could be perfect:

https://github.com/tarilabs/omlmd

by @tarilabs
