### ISSUE TITLE
Change install path to /var/usrlocal or /usr/local to support Atomic Systems

### ISSUE THREAD

**Issue by boredsquirrel** [containers/ramalama#177]
I would like to try this and will try to patch the install script.

Currently it doesnt work straight from the installer, as it downloads to an immutable directory.

Using /usr/share is one standard, but on Atomic Desktops, IoT and CoreOS it is considered a "protected system dir" so not meant to install stuff there.

**Comment by rhatdan** [comment]
You should be able install anywhere using 
make install PREFIX=/var/usr/local

But there will be an issue in the Python not being able to find the shared library, which would now be in /var/usr/local/lib/python3-12/site-packages/ramalama.

**Comment by ericcurtin** [comment]
The ramalama libs can be searched for via:

```
    sharedirs = ["/opt/homebrew/share/ramalama", "/usr/local/share/ramalama", "/usr/share/ramalama"]
    syspath = next((d for d in sharedirs if os.path.exists(d)), None)

    sys.path.insert(0, syspath)
```

the other python libs will be fine, will be in the standard places.

**Comment by ericcurtin** [comment]
And what I would expect to happen:

"/opt/homebrew/share/ramalama" # macOS ARM would use this
"/usr/local/share/ramalama" # Linux and macOS x86_64 would use this
"/usr/share/ramalama" # Nothing would use this, we can save this path for the rpm installed version

macOS ARM and macOS x86_64 is different, I know that's kinda weird, that's just the way macOS is designed because of Rosetta, etc.

**Comment by ericcurtin** [comment]
We have to support macOS x86_64 mainly because the github runners are macOS x86_64, so it's the only way to test macOS compatibility...

But in real life most macOS users will be using Apple Silicon...

**Comment by ericcurtin** [comment]
> You should be able install anywhere using make install PREFIX=/var/usr/local
> 
> But there will be an issue in the Python not being able to find the shared library, which would now be in /var/usr/local/lib/python3-12/site-packages/ramalama.

It is tempting to do more consolidation... And let the python install script call make... But we have to test make more on macOS... macOS make is different

**Comment by rhatdan** [comment]
Ramalama is now packaged via PyPi, which means it can be pip installed into a users account.

**Comment by ericcurtin** [comment]
Maybe even pipx... We have found problems with pip on Ubuntu and macOS @tarilabs found this also...

I'm planning on rewriting the curl | bash wrapper. But it will likely just be a wrapper for pipx

**Comment by tarilabs** [comment]
+1 for suggesting users to use pipx in the manual

**Comment by rhatdan** [comment]
SGTM

Still working on getting RPM packaging for Fedora and then move it to RHEL.

**Comment by ericcurtin** [comment]
Solved
