### ISSUE TITLE
Bug in parsing args with `--nocontainer` 

### ISSUE THREAD

**Issue by Ben-Epstein** [containers/ramalama#201]
If I run `ramalama --nocontainer run 'huggingface://bartowski/Phi-3.5-mini-instruct-GGUF/Phi-3.5-mini-instruct-Q6_K_L.gguf'`

I get the error 
```
--nocontainer and --name options conflict. --name requires a container.
```

Even though i didnt provide a --name flag.

Trying to debug, if I run
`ramalama --nocontainer run 'huggingface://bartowski/Phi-3.5-mini-instruct-GGUF/Phi-3.5-mini-instruct-Q6_K_L.gguf' --name ""`

I get `[1]    31484 illegal hardware instruction  ramalama --nocontainer run  --name ""` which at least seems to satisfy this  https://github.com/containers/ramalama/blob/85af8e877f608ba915a373fcb90cc6f1675ca3fa/ramalama/cli.py#L442C2-L445C1

I imagine this is some oddness with how argparse handles positional and optional args. Might be worth switching to typer or click for more determinism

**Comment by Ben-Epstein** [comment]
ah, here is why. The default install branch is `s` but in the `s` branch you check `args.name != ""` https://github.com/containers/ramalama/blob/s/ramalama/cli.py#L383

Shall we update that branch?

**Comment by rhatdan** [comment]
Yes

**Comment by ericcurtin** [comment]
's' branch is supposed to be more stable than main, so every now and then we do some testing and push to 's'. Will update 's' again soon

**Comment by rhatdan** [comment]
"Tough" to consider much stable at this point.  :^)

**Comment by rhatdan** [comment]
@ericcurtin Now that we have a PyPi package, it is probably time to create a 0.0.6 release.  So we can say that it is more stable.  Otherwise lets merge Main into S and close this issue.

**Comment by ericcurtin** [comment]
i think this is fixed
