### ISSUE TITLE
Apple silicon `illegal hardware instruction`

### ISSUE THREAD

**Issue by Ben-Epstein** [containers/ramalama#204]
I'm trying to run on an m3 Mac
```
ramalama --nocontainer run 'huggingface://bartowski/Phi-3.5-mini-instruct-GGUF/Phi-3.5-mini-instruct-Q6_K_L.gguf'
```

But i'm seeing 
```
[1]    34290 illegal hardware instruction  ramalama --nocontainer run
```

I believe it's an issue with llama.cpp though, seeing https://github.com/ggerganov/llama.cpp/issues/8065

**Comment by Ben-Epstein** [comment]
Closing this because its a llama-cpp issue https://github.com/ggerganov/llama.cpp/issues/9676

**Comment by ericcurtin** [comment]
Very tempted to try and lock down a llama.cpp version in brew, brew's llama.cpp package updates very frequently, too frequently, this is the second breaking change from llama.cpp in the last week it seems.

**Comment by rhatdan** [comment]
Yup, Not a huge fan of Brew for that reason.  But it is what people use.
