### ISSUE TITLE
podman ps on macOS

### ISSUE THREAD

**Issue by ericcurtin** [containers/ramalama#267]
$ bin/ramalama ps
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:49825: connect: connection refused

we don't use containers by default on macOS yet

**Comment by rhatdan** [comment]
Have you tried it with a podman machine?

ramalama --container ps

**Comment by ericcurtin** [comment]
It works great if podman machine is started.

We should either print a more informative message when we are not using containers, that `ramalama ps` is not supported when not using containers

or

maybe do some kind of a fancy pgrep for llama.cpp, vllm processes, etc. depending on runtime
