### ISSUE TITLE
During pipx install shortnames.conf is not being installed

### ISSUE THREAD

**Issue by ericcurtin** [containers/ramalama#288]
Ensure the file is installed and working for client-side shortnames

**Comment by rhatdan** [comment]
pipx is dropping this file for some reason.

**Comment by rhatdan** [comment]
pip install installs it.

**Comment by ericcurtin** [comment]
`.local//pipx/venvs/ramalama/share/ramalama/shortnames.conf`

This is an easy fix, I'll open a PR
