### ISSUE TITLE
insecure suggestion in documentation

### ISSUE THREAD

**Issue by ebblake** [containers/ramalama#289]
The home page suggests installation via a one-liner `curl ... | sudo sh` invocation.  This is inherently insecure - a bad actor able to inject an alternative file can take over a victim's machine.  Instead, the documentation should suggest using curl to download the file, manually inspecting its contents to ensure it has not been compromised (such as instructions on how to verify a checksum), and ONLY THEN to run the just-downloaded shell script.

(Yeah, I know that lots of projects have this bad hygiene of recommending the security hole of 'curl | sh', but I try to point it out everywhere that I see it)

**Comment by ericcurtin** [comment]
> The home page suggests installation via a one-liner `curl ... | sudo sh` invocation. This is inherently insecure - a bad actor able to inject an alternative file can take over a victim's machine. Instead, the documentation should suggest using curl to download the file, manually inspecting its contents to ensure it has not been compromised (such as instructions on how to verify a checksum), and ONLY THEN to run the just-downloaded shell script.
> 
> (Yeah, I know that lots of projects have this bad hygiene of recommending the security hole of 'curl | sh', but I try to point it out everywhere that I see it)

Well no, tell me how a bad actor would inject an alternate file here. It's literally backed by TLS, check the certificates:

https://social.treehouse.systems/@marcan/112489972769723170

We may get rid of the `curl | sudo sh` thing, but the security argument is weak when the file it TLS encrypted and verified. If people truly believe TLS downloaded things are insecure, they shouldn't use web browsers
