### ISSUE TITLE
Invalid args when installing with pipx

### ISSUE THREAD

**Issue by derrickqi2003** [containers/ramalama#305]
ramalama
invalid argument "RAMALAMA container" for "-l, --label" flag: label 'RAMALAMA container' contains whitespaces
See 'docker run --help'.

I receive this error with all ramalama commands. It works fine when I install ramalama with pip3 though.

**Comment by ericcurtin** [comment]
Hi @derrickqi2003 can you test if this change fixes your issue:

https://github.com/containers/ramalama/pull/306

we haven't thoroughly tested docker support yet. Just podman support and without containers at all. It should only take a handful of changes to get docker working and we can add docker to CI to make sure it's continually tested for compatibility.

**Comment by derrickqi2003** [comment]
Hi,
Didn't figure out how to test your change until after the change was merged. Issue was fixed with that change. Thanks!
