### ISSUE TITLE
Replace huggingface-cli with simple client that pulls models over https

### ISSUE THREAD

**Issue by ericcurtin** [containers/ramalama#335]
We can just pull .gguf files using a url formulated like this:

https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF/resolve/main/mixtral-8x7b-v0.1.Q4_K_M.gguf

one less dependancy needed huggingface-cli isn't packaged widely.

**Comment by ericcurtin** [comment]
@swarajpande5 might be interested in taking this on

**Comment by swarajpande5** [comment]
@ericcurtin Yes please, assign this to me.

**Comment by swarajpande5** [comment]
@ericcurtin @rhatdan Do we need to preserve the push model functionality of the Huggingface class ?

**Comment by ericcurtin** [comment]
@swarajpande5 what we can do is:

Remove huggingface-cli as a dependancy
Leave the push code as is (if people really want to install huggingface-cli to push, they can)
Re-implement the pull code just using python http client code, sorta like our Ollama client code

**Comment by swarajpande5** [comment]
Yeah, this sounds good 👍🏼

**Comment by rhatdan** [comment]
I think remove the push and leave it as not currently supported since it does not work.

Remove hugginface_cli from pyproject.toml and python-ramalama.spec.
