### ISSUE TITLE
Install script fails

### ISSUE THREAD

**Issue by vpavlin** [containers/ramalama#336]
Hi all, I tried to install ramalama and got an error

```
$ curl -fsSL https://raw.githubusercontent.com/containers/ramalama/s/install.sh | sudo sh
sh: 64: Syntax error: "(" unexpected (expecting "}")
```

OS: Ubuntu 23.10

**Comment by ericcurtin** [comment]
Fix:

https://github.com/containers/ramalama/pull/337

Please use:

`curl -fsSL https://raw.githubusercontent.com/containers/ramalama/s/install.sh | sudo bash`

instead

**Comment by rhatdan** [comment]
Fixed.
