### ISSUE TITLE
Error trying to pull ramalama:latest-rocm: manifest unknown

### ISSUE THREAD

**Issue by Chevek** [containers/ramalama#359]
Fedora 40 with an AMD GPU (RADEON RX 7900 XTX):

I have this error when trying to run ramalama:
$ ramalama
Trying to pull quay.io/ramalama/ramalama:latest-rocm...
Error: initializing source docker://quay.io/ramalama/ramalama:latest-rocm: reading manifest latest-rocm in quay.io/ramalama/ramalama: manifest unknown

**Comment by ericcurtin** [comment]
You can apply this patch:

https://github.com/containers/ramalama/pull/360

Or just run this and it should work:

ramalama --image quay.io/ramalama/ramalama:latest run

Sorry we changed the container name urls. That's a pretty mean GPU with loads of VRAM. Interested to see what kinda results you get there 😎
