### ISSUE TITLE
Podman Path Mounting Error and Llama-cli Incorrect Path

### ISSUE THREAD

**Issue by bmahabirbu** [containers/ramalama#413]
I'm getting an error that prevents Ramalama from starting the container. It seems like with Podman's new arguments the AI model name is incorrectly being referenced without the associated path and then trying to mount it on /mnt/models. 
```
bmahabir@DESKTOP-SB69448:~/ramalama$ podman --version
podman version 3.4.4
```
```
python3 bin/ramalama --debug run llama3

podman run \
  --rm \
  -i \
  --label RAMALAMA \
  --security-opt=label=disable \
  --name ramalama_ENqL2e2TBv \
  -v /home/bmahabir/.local/share/ramalama:/var/lib/ramalama \
  -t \
  --device /dev/dri \
  --mount type=image,src=llama3,destination=/mnt/models,rw=false \ # This command just specifies llama3
  quay.io/ramalama/ramalama:latest \
  llama-cli \
  -m /home/bmahabir/.local/share/ramalama/models/ollama/llama3:latest \ # This should be the container path with the mount not the host
  --in-prefix "" \
  --in-suffix "" \
  -p "You are a helpful assistant" \  # Prefix for model prompt
  -c 2048 \
  -cnv
```
```
ERRO[0000] error cleaning up container cb30dcbd623d8ab1aa482a20b8cc8b76287c7979fe607b327e3332212106ac42: llama3: image not known
Error: error creating image volume "llama3":"/mnt/models": llama3: image not known
bmahabir@DESKTOP-SB69448:~/ramalama$
```

Also Llama.cpp is now looking at the host path for the model rather than /var/lib/ramalama/*

Here is an example of a fixed command string that works for me

```
podman run \
  --rm \
  -i \
  --label RAMALAMA \
  --security-opt=label=disable \
  --name ramalama_QUUahCQqQ5 \
  -v /home/bmahabir/.local/share/ramalama:/var/lib/ramalama \
  -t \
  --device /dev/dri \
  --mount type=bind,src=/home/bmahabir/.local/share/ramalama/models/ollama/llama3:latest,destination=/mnt/models,rw=false \ # Fixed
  quay.io/ramalama/ramalama:latest \
  llama-cli \
  -m /var/lib/ramalama/models/ollama/llama3:latest \ # Adds correct path
  --in-prefix "" \
  --in-suffix "" \
  -p "You are a helpful assistant" \
  -c 2048 \
  -cnv

```
This will mount the ai models to /mnt/models and llama-cli looks in the correct spot inside the container for the ai model

**Comment by bmahabirbu** [comment]
There are 2 mounts /var/lib* and /mnt/models. Should the models just be mounted on /mnt/models?

**Comment by rhatdan** [comment]
Does https://github.com/containers/ramalama/pull/414 fix the problem?

We need a way in the CI/CD system to test ramamage run and ramalama serve, to make sure these regressions do not happen.

Basically we need a one line ramalama run command that exits after using user input.

**Comment by bmahabirbu** [comment]
I'm still getting the issue using the "run" command but "serve" works

This is the output for run
```
 --mount=type=image,src=llama3,destination=/mnt/models
```
And this is the output for serve
```
--mount=type=bind,src=/home/bmahabir/.local/share/ramalama/models/ollama/llama3:latest,destination=/mnt/models/model.file
```
Serve has the correct path, uses bind instead of image, and mounts it correctly to /mnt/models/model.file instead of just /mnt/models
