### ISSUE TITLE
Create CONTRIBUTING.md to guide new contributors

### ISSUE THREAD

**Issue by jwflory** [containers/ramalama#502]
# Summary

It is not clear how to contribute to RamaLama and there is no documentation about how to contribute.

# Background

The README states that the project is open to contributors and the [Flock 2024 presentation](https://cfp.fedoraproject.org/media/flock-2024/submissions/HM9Y8U/resources/ramalama__Introducing_the_Boring_AI_Companion_0oOoOwG.pdf) claimed the project was contributor-friendly, but there is no guidance, documentation, or help on how to contribute to RamaLama. I could not find documentation about how to set up a dev environment.

A little bit of attention to the newcomer experience will make good on the Flock 2024 claim that the project is contributor-friendly, because I found it confusing to figure out how to contribute to the project and what kinds of contributions were desired.

# Details

The best place to start would be to create a `CONTRIBUTING.md` file that includes instructions on how to set up a developer environment, how to test a contribution, and expectations for Pull Request review. It would also be good to communicate expectations to a potential contributor, e.g. "new PRs will be reviewed within 10 working days."

There is always more that a project can do here, but making the first step is always the best step!

# Outcome

- New contributors can better understand how to participate and contribute to RamaLama
- Improve on open source best practices and make the project more inclusive to new contributors

**Comment by caradelia** [comment]
Thanks @jwflory. A contributing.md is on the list as we build out the community.

**Comment by jwflory** [comment]
Thanks @caradelia for lightning-fast follow-up! 🙏🏻 It is great to know that it is already on the list. It will go a long way to activating more folks from community to participate, when they see the pathway for how to contribute and importantly, what kind of contributions the team is capable of accepting at this time.

Also, if it were helpful, I could share this call for help in writing a `CONTRIBUTING.md` file with the Fedora community, because I think RamaLama is an interesting project to Fedora-adjacent folks. Let me know if it would be helpful to solicit this assistance, and I could make a wider call for help on this in Fedora community channels.

**Comment by rhatdan** [comment]
I think there is a global contributing.md for the containers projects. But I don't know how to show it on the ramalama site.

@TomSweeneyRedHat Any ideas?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan we have used https://github.com/containers/common/blob/main/CONTRIBUTING.md
