### ISSUE TITLE
Create `ramalama run granite-code "Some prompt"`

### ISSUE THREAD

**Issue by ericcurtin** [containers/ramalama#69]
That's deliver a single user prompt waits for a response and exits

**Comment by rhatdan** [comment]
Would ramalama run granite-code --prompt "some prompt" be better.
I would think
ramalama run granite-code "some prompt" 

Would run the chatbot with a single "string" and then exit.

IE get the AI Model to process the "some prompt" string to STDOUT and then exit.

**Comment by ericcurtin** [comment]
Sorry this is what I mean for this feature:

`Would run the chatbot with a single "string" and then exit.`

Like Ollama does...

I am speaking about a single user prompt in this issue... "Write me a poem about flowers"

I think the prompt you are referring to is the system prompt? "You are Dan Walsh writer of Podman in Action"

**Comment by ericcurtin** [comment]
I rewrote this issue, it was incorrectly written the first time.

**Comment by rhatdan** [comment]
I believe this is fixed now? Closng.
