### ISSUE TITLE
Provide binaries / reasoning for using Python vs Go?

### ISSUE THREAD

**Issue by cdrage** [containers/ramalama#72]
Maybe opening a can of worms, but I'm curious the reasoning for using Python vs other static languages so that a binary could be provided vs installing via `python install.py` ?

**Comment by p5** [comment]
Also curious on this, though if there's some documentation for aliasing `ramalama` to the relevant `podman run`/`docker run` commands (as seen in some other projects like [rustscan](https://github.com/RustScan/RustScan/wiki/Installation-Guide#:~:text=You%20will%20have,rustscan%3A2.1.1%27)), this removes the runtime dependency for Python on the host, which would be great.

**Comment by ericcurtin** [comment]
We debated golang, Rust, C, C++, bash, python for this... The first version was written in bash...

python as a runtime dependency really isn't that bad, when macOS and Linux are your target platforms...

Although... we really don't want to be pulling in all sorts of python libraries...

We aim to be podman-like, but there will never be strict aliasing between ramalama, podman and docker...

**Comment by rhatdan** [comment]
I feel that the barrier to entry for Python is much lower then other languages.  The goal is to get contributors to the project.  Most of ramalama is wrapping other executables like podman, lama.cpp, vllm, huggingface-cli etc, and Python is tremendous at doing this.

**Comment by ericcurtin** [comment]
I'm gonna close this one, but if someone wants to write up the pros/cons of python vs go, that's fine... Maybe don't put it on the main README.md . A user shouldn't care too much about languages used in ramalama.
