### ISSUE TITLE
Create container images latest-cuda, latest-vulkan, latest-rocm

### ISSUE THREAD

**Issue by ericcurtin** [containers/ramalama#93]
Use UBI9 if possible

latest-cuda will go something like this:

dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo
dnf install -y libcudnn8 nvidia-driver-NVML nvidia-driver-cuda-libs

Build with

GGML_CUDA=1

latest-rocm will go something like this:

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/native-install/rhel.html

GGML_ROCM=1 # or whatever the flag is called

latest-vulkan will have to work with @slp's patches with kompute (may require a mix of CentOS Stream 9 and UBI packages):

Test all containers with a real GPU and get automated with @cooktheryan so these are built automatically and available to users.

**Comment by ericcurtin** [comment]
@LC-JiaZhaorong you have been reported to GitHub in the category of Phishing, but genuinely god knows what's behind that link...

No-one touch that link please

**Comment by rhatdan** [comment]
We now have a rocm and vulkan(cpuonly) container image.

**Comment by rhatdan** [comment]
We have all three, closing.
